spring.config.import=classpath:version.properties

#Datenbank Einstellungen
spring.datasource.url=jdbc:sqlite:data.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hikari Einstellungen
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1

# Automatisches Anlegen/Aktualisieren der Tabellen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Metrics Einstellungen
collectd.host=localhost
collectd.port=25826