name: CI for Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      message:
        description: 'A custom message to trigger this workflow'
        required: true
        default: 'Triggering workflow'

      version:
        description: 'Specify Java version'
        required: true
        default: '21'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [21]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Test with Maven
      run: mvn clean install


    - name: Run Maven Tests
      run: mvn clean verify -DdisplayName=true -B


    - name: Print Maven Test Results
      shell: bash
      run: |
        echo "Maven Test Results:"
        if [ -d target/surefire-reports ]; then
          cat target/surefire-reports/*.txt
        else
          echo "No test results found."
        fi